// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm5nmdJoHKkwW2ONKRalcsNzDdNrxQ0_0',
    appId: '1:59665215731:web:89f085f9a6d0bac9e54786',
    messagingSenderId: '59665215731',
    projectId: 'docconnect-mvp',
    authDomain: 'docconnect-mvp.firebaseapp.com',
    storageBucket: 'docconnect-mvp.firebasestorage.app',
    measurementId: 'G-59M6BGGHXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPIjl1gLJWGXbJK47dFW-tR97POEg1q-s',
    appId: '1:59665215731:android:3ae0ef20b5e4a8c4e54786',
    messagingSenderId: '59665215731',
    projectId: 'docconnect-mvp',
    storageBucket: 'docconnect-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUVSGrxpq2O_ZaSCPNzAmxnWbzJg84rb0',
    appId: '1:59665215731:ios:620898161ca73edfe54786',
    messagingSenderId: '59665215731',
    projectId: 'docconnect-mvp',
    storageBucket: 'docconnect-mvp.firebasestorage.app',
    iosBundleId: 'com.docconnect.app.docconnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUVSGrxpq2O_ZaSCPNzAmxnWbzJg84rb0',
    appId: '1:59665215731:ios:620898161ca73edfe54786',
    messagingSenderId: '59665215731',
    projectId: 'docconnect-mvp',
    storageBucket: 'docconnect-mvp.firebasestorage.app',
    iosBundleId: 'com.docconnect.app.docconnectApp',
  );
}
